# Demo workflow 1 : Getting started
name: Demo Workflow 1
on: 
  push:
    branches: 
      - master
  workflow_dispatch:
jobs: 
  first_job:
    name: job 1
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "Hello world from ${{ github.actor }}."
          echo "Current branch is '${{ github.ref }}'."
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - run: tree
